baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Entre deux mondes"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
paginate = 6

[params]
images = ["img/7cc68a58-0d1f-4d1e-918e-c5ceb9a4b998.webp"]

[permalinks]
post = "/:title/"